# from django.conf.urls import url
import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from CMDB.views import *
from django.views.generic import TemplateView
from django.conf.urls.static import static

# hosts_info = {
#      'hosts' : Hosts.objects.all(),
#      'template_name' : 'hosts_list_page.html',
# }


urlpatterns = [
    # url(r'^ueditor/',include('DjangoUeditor.urls' )),
    url(r'^$', homepage),
    url(r'^admin/', admin.site.urls),
    url(r'^hostlist/$', hostlist),
    url(r'^boot/$', boot),
    # url(r'^search-form/$', search_form),
    url(r'^search/$', search),
    url(r'^index/$', index_1),
    url(r'^report/$', report),
    url(r'^modelname/$', modelname),
    url(r'^domain/$', domain),
    url(r'^fu/$', fu),
    url(r'^even/$', even),
    url(r'^login/$', account_login),
    url(r'^hosts/$', hosts),
    url(r'^data/$', data),
    url(r'^ajax_list/$', ajax_list),
    url(r'^zabbix_get/$', zabbix_get),
    url(r'^ratio/$', ratio),
    url(r'^items/$', items),
    url(r'^online/$', online_web),
    url(r'^online_app/$', online_app),
    url(r'^json_host/$', json_host),
    url(r'^item_data/$', item_data),
    url(r'^showlog/$', showlog_web),
    url(r'^showlog_app/$', showlog_app),
    url(r'^supervisor/$', supervisor),
    url(r'^control/$', control),
    url(r'^ajax_online/$', ajax_online),
    # url(r'^list/$', test_view.as_view()),
    url(r'^fre_host/$', fre_host),
    url(r'^fre_log/$', fre_log),
    url(r'^new/$', new),
    url(r'^new_hosts/$', new_hosts),
    url(r'^new_online/$', new_online_web),
    url(r'^new_modelname/$', new_modelname),
    url(r'^new_domain/$', new_domain),
    url(r'^new_items/$', new_items),
    url(r'^new_supervisor/$', new_supervisor),
    url(r'^new_report/$', new_report),
    url(r'^openFile/$', openFile),
    url(r'^updatefile/$', updatefile),
    url(r'^config_manage/$', config_manage),
    url(r'^config_data/$', config_data),
    url(r'^config_update/$', config_update),
    url(r'^ajax_config/$', ajax_config),
    url(r'^config_syn/$', config_syn),
    url(r'^backup_config/$', backup_config),
    url(r'^mulfile/$', mulfile,name='mulfile'),
    url(r'^get_modelname/$', get_modelname),
    url(r'^mulcomm/$', mulcomm),
    url(r'^mulshell/$', mulshell),
    url(r'^list/$', list, name='list'),
    url(r'^sendfile/$',sendfile),
    url(r'^dbsize/$',redis_db),
    url(r'^mysql_rsy/$',mysql_db),
    url(r'^weixin/$', weixin_test),
    url(r'^weixin_check/$', weixin_check),
    url(r'^chanell/$', chanell),
    url(r'^chanell_check/$', chanell_check),
    url(r'^chanell_get/$',chanell_get),
    url(r'^chanell_history/$',chanell_history),
    url(r'^get_share_domain_list/$', get_share_domain_list),
    url(r'^usedomain/$', usedomain),
    url(r'^checkdomain/$', checkdomain),
    url(r'^send/$', send_message),
    url(r'^monitordomain/$', monitor_domain),
    url(r'^add_domain/$', add_domain),
    url(r'^drop_domain/$', drop_domain),
    url(r'^coohua_sharedomain/$', coohua_share_domain_list),
    url(r'^imdomain/$', domain_import_web),
    url(r'^domain_import/$', domain_import),
    url(r'^coohua_jusharedomain/$', coohua_share_count),
    url(r'^domain_muimport/$', domain_muimport),
    url(r'^show_mu_domain/$', show_mu_domain),
    url(r'^drop_nu_domain/$', drop_nu_domain),
    url(r'^domain_pool_web/$', domain_pool_web),
    url(r'^domainpool_import/$',domainpool_import),
    url(r'^drop_domain_pool/$',drop_domain_pool),
    url(r'^get_pool_domain/$',get_pool_domain),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
