# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brothers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='chanell_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_x', models.IntegerField(blank=True, null=True)),
                ('hourly_y', models.IntegerField(blank=True, null=True)),
                ('date_a', models.IntegerField(blank=True, null=True)),
                ('date_b', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('models_name', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(blank=True, max_length=100)),
                ('describe', models.CharField(blank=True, max_length=250)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('remote_user', models.CharField(blank=True, max_length=50)),
                ('playbook_path', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='coohua_share_domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('reg_date', models.CharField(blank=True, max_length=50, null=True)),
                ('last_date', models.CharField(blank=True, max_length=50, null=True)),
                ('weixin_status', models.IntegerField(blank=True, null=True)),
                ('qq_status', models.IntegerField(blank=True, null=True)),
                ('deny_date', models.CharField(blank=True, max_length=50, null=True)),
                ('use_date', models.CharField(blank=True, max_length=50, null=True)),
                ('res_sta', models.IntegerField(blank=True, null=True)),
                ('Sponsoring_Registrar', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dbsize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('bj_ip', models.CharField(blank=True, max_length=50)),
                ('qd_ip', models.CharField(blank=True, max_length=50)),
                ('qd_s_ip', models.CharField(blank=True, default=0, max_length=50)),
                ('qd_s_wip', models.CharField(blank=True, default=0, max_length=50)),
                ('qd_s_size', models.CharField(blank=True, default=0, max_length=50)),
                ('qd_size', models.IntegerField(blank=True, default=0, null=True)),
                ('bj_size', models.IntegerField(blank=True, default=0, null=True)),
                ('bj_status', models.CharField(blank=True, max_length=50, null=True)),
                ('diff_size', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deny_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_name', models.CharField(max_length=100)),
                ('models_count', models.IntegerField(blank=True, null=True)),
                ('date_time', models.CharField(max_length=20)),
                ('cost_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('usename', models.CharField(blank=True, max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('remark', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='domain_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.CharField(max_length=100)),
                ('pool_count', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('domain_count', models.IntegerField(blank=True, null=True)),
                ('qq_status', models.IntegerField(blank=True, null=True)),
                ('weixin_status', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('lip', models.CharField(max_length=15)),
                ('wip', models.CharField(blank=True, max_length=15)),
                ('config', models.CharField(max_length=250)),
                ('data_center', models.IntegerField()),
                ('environment', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('cost', models.FloatField(blank=True)),
                ('remark', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='iterms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('cpu_itemid', models.IntegerField(blank=True, null=True)),
                ('cpu_idle', models.FloatField(blank=True, null=True)),
                ('cpu_graphs_itemsid', models.IntegerField(blank=True, null=True)),
                ('eth0_graphs_itemsid', models.IntegerField(blank=True, null=True)),
                ('eth1_graphs_itemsid', models.IntegerField(blank=True, null=True)),
                ('memory_total_itemsid', models.IntegerField(blank=True, null=True)),
                ('memory_total', models.FloatField(null=True)),
                ('memory_available_itemsid', models.IntegerField(blank=True, null=True)),
                ('memory_available', models.FloatField(null=True)),
                ('eth0_in_itemsid', models.IntegerField(blank=True, null=True)),
                ('eth0_in', models.FloatField(null=True)),
                ('eth0_out_itemsid', models.IntegerField(blank=True, null=True)),
                ('eth0_out', models.FloatField(null=True)),
                ('eth1_in_itemsid', models.IntegerField(blank=True, null=True)),
                ('eth1_in', models.FloatField(null=True)),
                ('eth1_out_itemsid', models.IntegerField(blank=True, null=True)),
                ('eth1_out', models.FloatField(null=True)),
                ('cpu_load_itemsid', models.IntegerField(blank=True, null=True)),
                ('cpu_load', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='k8s_depoloy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('lead', models.CharField(blank=True, max_length=50, null=True)),
                ('json_path', models.CharField(default='CMDB/scripts/playbooks/k8s/vars-json/', max_length=200)),
                ('img_address', models.CharField(default='registry.cn-beijing.aliyuncs.com/coohua_img/', max_length=250)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('img_version', models.CharField(blank=True, max_length=20, null=True)),
                ('war_path', models.CharField(blank=True, max_length=200, null=True)),
                ('war_name', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('lead', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=250)),
                ('deploy', models.CharField(default='/app/coohua/publish/deploy/deploy.sh', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='monitordomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('weixin_status', models.IntegerField(blank=True, null=True)),
                ('qq_statu', models.IntegerField(blank=True, default=1, null=True)),
                ('remark', models.CharField(max_length=200)),
                ('last_date', models.DateTimeField(auto_now_add=True)),
                ('deny_time', models.CharField(blank=True, max_length=50, null=True)),
                ('qq_deny_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='monitordomain_qq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('qq_statu', models.IntegerField(blank=True, default=1, null=True)),
                ('remark', models.CharField(max_length=200)),
                ('last_date', models.DateTimeField(auto_now_add=True)),
                ('qq_deny_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mysql_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=50)),
                ('qd_table_size', models.IntegerField(blank=True, default=0, null=True)),
                ('bj_table_size', models.IntegerField(blank=True, default=0, null=True)),
                ('diff_size', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ngx_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('api', models.CharField(max_length=200)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ngx_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_name', models.CharField(blank=True, max_length=20)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('describe', models.CharField(blank=True, max_length=250)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('playbook_path', models.CharField(blank=True, max_length=250)),
                ('describe', models.CharField(blank=True, max_length=250)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='share_domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
                ('reg_date', models.CharField(blank=True, max_length=50, null=True)),
                ('last_date', models.CharField(blank=True, max_length=50, null=True)),
                ('weixin_status', models.IntegerField(blank=True, null=True)),
                ('deny_date', models.CharField(blank=True, max_length=50, null=True)),
                ('use_date', models.CharField(blank=True, max_length=50, null=True)),
                ('res_sta', models.IntegerField(blank=True, null=True)),
                ('Sponsoring_Registrar', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='supervisor_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su_hostname', models.CharField(max_length=200)),
                ('su_url', models.CharField(max_length=200)),
                ('su_remark', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='./upload/')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='zaker_spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('top_img', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('source_site', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hosts',
            name='Modelname',
            field=models.ManyToManyField(blank=True, to='CMDB.Modelname'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='server',
            field=models.ManyToManyField(blank=True, to='CMDB.Server'),
        ),
        migrations.AddField(
            model_name='history',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.Hosts'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.Brothers'),
        ),
        migrations.AddField(
            model_name='domain',
            name='service_model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.Modelname'),
        ),
        migrations.AddField(
            model_name='brothers',
            name='service',
            field=models.ManyToManyField(to='CMDB.Modelname'),
        ),
    ]
