# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brothers',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='environment',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='lead',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
