# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_auto_20160201_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('usename', models.CharField(blank=True, max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('remark', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hosts',
            options={'ordering': ['hostname']},
        ),
        migrations.AlterField(
            model_name='brothers',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='remark',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='config',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='instance_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='remark',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='server',
            field=models.ManyToManyField(blank=True, to='CMDB.Server'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='service_model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.Services'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='wip',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='lead',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='services',
            name='remark',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='domain',
            name='service_model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.Services'),
        ),
    ]
