# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0003_auto_20160223_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='iterms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField()),
                ('hostname', models.IntegerField()),
                ('cpu_itemid', models.FloatField(blank=True)),
                ('cpu_graphs_itemsid', models.IntegerField(blank=True)),
                ('eth0_graphs_itemsid', models.IntegerField(blank=True)),
                ('eth1_graphs_itemsid', models.IntegerField(blank=True)),
            ],
        ),
    ]
