# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0004_calendarevent_iterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterms',
            name='cpu_idle',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='iterms',
            name='hostname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
