# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0005_auto_20160318_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterms',
            name='cpu_load',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='cpu_load_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='eth0_in',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='eth0_in_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='eth0_out',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='eth0_out_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='eth1_in',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='eth1_in_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='eth1_out',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='eth1_out_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='memory_available',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='memory_available_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='memory_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iterms',
            name='memory_total_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iterms',
            name='cpu_idle',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='iterms',
            name='cpu_itemid',
            field=models.IntegerField(blank=True),
        ),
    ]
