# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0006_auto_20160324_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iterms',
            name='cpu_graphs_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iterms',
            name='cpu_idle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iterms',
            name='cpu_itemid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iterms',
            name='eth0_graphs_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iterms',
            name='eth1_graphs_itemsid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
