# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0007_auto_20160326_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_name', models.CharField(blank=True, max_length=20)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('describe', models.CharField(blank=True, max_length=250)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
