# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0008_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='version',
            field=models.FloatField(null=True),
        ),
    ]
