# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0009_auto_20160526_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='service_model',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
