# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0010_auto_20160624_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='service_model',
        ),
        migrations.AddField(
            model_name='hosts',
            name='model',
            field=models.ManyToManyField(blank=True, to='CMDB.Services'),
        ),
    ]
