# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0011_auto_20160726_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosts',
            old_name='model',
            new_name='service_model',
        ),
    ]
