# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0012_auto_20160726_0620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Modelname',
        ),
        migrations.RenameField(
            model_name='hosts',
            old_name='service_model',
            new_name='Modelname',
        ),
    ]
