# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0013_auto_20160726_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(null=True)),
                ('models_name', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(blank=True, max_length=100)),
                ('describe', models.CharField(blank=True, max_length=250)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
