# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0014_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
