# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0015_auto_20160805_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['models_name']},
        ),
    ]
