# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0016_auto_20160805_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={},
        ),
    ]
