# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0017_auto_20160805_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='playbook_path',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='config',
            name='remote_user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
