# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-30 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0018_auto_20160817_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes', verbose_name='Imagen')),
            ],
        ),
    ]
