# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-31 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0020_auto_20160830_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('headImg', models.FileField(upload_to='/upload/')),
            ],
        ),
    ]
