# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0023_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
