# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-30 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0024_auto_20160914_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='Modelname',
            field=models.ManyToManyField(blank=True, null=True, to='CMDB.Modelname'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='server',
            field=models.ManyToManyField(blank=True, null=True, to='CMDB.Server'),
        ),
    ]
