# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0025_auto_20161030_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbsize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('bj_ip', models.CharField(blank=True, max_length=50)),
                ('qd_size', models.IntegerField(blank=True)),
                ('bj_size', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hosts',
            name='Modelname',
            field=models.ManyToManyField(blank=True, to='CMDB.Modelname'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='server',
            field=models.ManyToManyField(blank=True, to='CMDB.Server'),
        ),
    ]
