# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0026_auto_20161107_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbsize',
            name='bj_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dbsize',
            name='bj_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dbsize',
            name='qd_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
