# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0027_auto_20161107_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbsize',
            name='bj_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
