# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0028_auto_20161107_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsize',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dbsize',
            name='qd_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
