# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0029_auto_20161120_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='mysql_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('qd_table_size', models.IntegerField(blank=True, null=True)),
                ('bj_table_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
