# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-22 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0030_mysql_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql_count',
            name='database_name',
            field=models.CharField(default=datetime.datetime(2016, 11, 22, 10, 17, 54, 333339, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
