# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-23 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0031_mysql_count_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsize',
            name='diff_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mysql_count',
            name='diff_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dbsize',
            name='bj_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dbsize',
            name='qd_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mysql_count',
            name='bj_table_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mysql_count',
            name='qd_table_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
