# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-23 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0032_auto_20161123_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsize',
            name='bj_status',
            field=models.CharField(default=datetime.datetime(2016, 11, 23, 8, 9, 12, 891836, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
