# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0033_dbsize_bj_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbsize',
            name='bj_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
