# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-23 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0034_auto_20161123_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsize',
            name='qd_s_ip',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='dbsize',
            name='qd_s_size',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
